# font=GeistMono Nerd Font:size=14
font=JetBrainsMono Nerd Font:size=14
pad=6x6 

[colors-dark]
foreground=b2b2b2
background=080808

regular0=323437  # black
regular1=ff5454  # red
regular2=8cc85f  # green
regular3=e3c78a  # yellow
regular4=80a0ff  # blue
regular5=cf87e8  # magenta
regular6=79dac8  # cyan
regular7=c6c6c6  # white

bright0=949494
bright1=ff5189
bright2=36c692
bright3=c2c292
bright4=74b2ff
bright5=ae81ff
bright6=85dc85
bright7=e4e4e4

dim0=323437
dim1=ff5454
dim2=8cc85f
dim3=e3c78a
dim4=80a0ff
dim5=cf87e8
dim6=79dac8
dim7=c6c6c6

selection-background=b2ceee
selection-foreground=080808

# [colors-dark]
# foreground=acb4c2
# background=011627
# 
# regular0=1d3b53  # black
# regular1=fc514e  # red
# regular2=a1cd5e  # green
# regular3=e3d18a  # yellow
# regular4=82aaff  # blue
# regular5=c792ea  # magenta
# regular6=7fdbca  # cyan
# regular7=aac1e0  # white
# 
# bright0=7c8f8f
# bright1=ff5874
# bright2=21c7a8
# bright3=ffe37e
# bright4=82aaff
# bright5=c792ea
# bright6=7fdbca
# bright7=d6deeb
# 
# dim0=162a3a  # dim black
# dim1=cc4a4a  # dim red
# dim2=7fb77e  # dim green
# dim3=c2a86b  # dim yellow
# dim4=5f8dd3  # dim blue
# dim5=a37acc  # dim magenta
# dim6=63bfb3  # dim cyan
# dim7=7f93b3  # dim white

alpha=0.90
