#!/usr/bin/env bash

# Icons
WIFI_ICON=$HOME/.config/hypr/assets/wifi.png
NOTIFICATIONS_ICON=$HOME/.config/hypr/assets/notifications.png
BLUETOOTH_ICON=$HOME/.config/hypr/assets/bluetooth.png

BLUETOOTH_STATE=$(bluetoothctl show | grep Powered: | awk '{print $2}')
WIFI_STATE=$(nmcli radio wifi)
NOTIFICATIONS_STATE=$(dunstctl is-paused)

# INFO: First argument is an Image, second is the service and the third is the state
notify_user() {
	notify-send -t 1800 -u normal -i "$1" "$2: $3"
}

bluetooth() {
	if [[ "$BLUETOOTH_STATE" == "yes" ]]; then
		bluetoothctl power off
		notify_user "$BLUETOOTH_ICON" "Bluetooth" "OFF"
	else
		bluetoothctl power on
		notify_user "$BLUETOOTH_ICON" "Bluetooth" "ON"
	fi
}

wifi() {
	if [[ "$WIFI_STATE" == "enabled" ]]; then
		nmcli radio wifi off
		notify_user "$WIFI_ICON" "Wifi" "OFF"
	elif [[ "$WIFI_STATE" == "disabled" ]]; then
		nmcli radio wifi on
		notify_user "$WIFI_ICON" "Wifi" "ON"
	fi
}

notify() {
	if [[ "$NOTIFICATIONS_STATE" == "false" ]]; then
		notify_user "$NOTIFICATIONS_ICON" "Notifications" "OFF"
		sleep 2
		dunstctl set-paused true
	else
		dunstctl set-paused false
		sleep 1
		notify_user "$NOTIFICATIONS_ICON" "Notifications" "ON"
	fi
}

if [[ "$1" == "-b" ]]; then
	bluetooth
elif [[ "$1" == "-w" ]]; then
	wifi
elif [[ "$1" == "-n" ]]; then
	notify
else
	exit 1
fi
