#!/usr/bin/env bash

dunst &
waybar &
eww daemon
wl-paste --type text --watch cliphist store &
wl-paste --type image --watch cliphist store &
swww init
wallpaper ~/Pictures/Wallpapers/ --randomize &
wlsunset -t 3400 -T 3401 &
display_select
# riverctl spawn "wlr-randr --output eDP-1 --mode 1920x1080 --pos 1920,0 --transform normal --output HDMI-A-1 --preferred --mode 1920x1080 --pos 0,0 --transform normal"
