#!/usr/bin/env bash

# Variables
VOL_ICON=$HOME/.config/river/assets/volume.png
MIC_ICON=$HOME/.config/river/assets/microphone.png

get_volume() {
	volume_wpctl=$(wpctl get-volume @DEFAULT_AUDIO_SINK@ | awk '{print $2}')
	volume=$(echo "scale=0; $volume_wpctl * 100" | bc)
	# volume=$(amixer sget Master | grep 'Right:' | awk -F'[][]' '{ print $2 }' | sed -e 's/%//')
	echo "$volume"
}

get_mute() {
	mute=$(amixer sget Master | grep 'Right:' | awk -F'[][]' '{ print $4 }')
	echo "$mute"
}

notify_user() {
	notify-send -t 1000 -u normal -i "$VOL_ICON" "Volume : $(get_volume) %"
}

inc_volume() {
	wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 2%+ && notify_user
}

dec_volume() {
	wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 2%- && notify_user
}

toggle_mute() {
	wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle && notify-send -t 1000 -u normal -i "$VOL_ICON" "Volume $(get_mute)"
}

toggle_mic() {
	wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle && notify-send -t 1000 -u normal -i "$MIC_ICON" "Microphone $(get_mic_mute)"
}

get_mic() {
	mic_wpctl=$(wpctl get-volume @DEFAULT_AUDIO_SOURCE@ | awk '{print $2}')
	mic=$(echo "scale=0; $mic_wpctl * 100" | bc)
	# mic=$(amixer sget Capture | grep 'Right:' | awk -F'[][]' '{ print $2 }' | sed -e 's/%//')
	echo "$mic"
}

get_mic_mute() {
	mute=$(amixer sget Capture | grep 'Right:' | awk -F'[][]' '{ print $4 }')
	echo "$mute"
}

notify_mic_user() {
	notify-send -t 1000 -u normal -i "$MIC_ICON" "Microphone : $(get_mic) %"
}

inc_mic_volume() {
  wpctl set-volume -l 1 @DEFAULT_AUDIO_SOURCE@ 2%+ && notify_mic_user
}

dec_mic_volume() {
  wpctl set-volume -l 1 @DEFAULT_AUDIO_SOURCE@ 2%- && notify_mic_user
}

if [[ "$1" == "--get_volume" ]]; then
	get_volume
elif [[ "$1" == "--inc" ]]; then
	inc_volume
elif [[ "$1" == "--dec" ]]; then
	dec_volume
elif [[ "$1" == "--toggle" ]]; then
	toggle_mute
elif [[ "$1" == "--toggle_mic" ]]; then
	toggle_mic
elif [[ "$1" == "--inc_mic" ]]; then
	inc_mic_volume
elif [[ "$1" == "--dec_mic" ]]; then
	dec_mic_volume
else
	get_volume
fi
