#!/usr/bin/env bash

# If the operating system is not Arch Linux, exit the script successfully
if [ ! -f /etc/arch-release ]; then
    exit 0
fi

AUR=$(paru -Qua | wc -l)
PACMAN=$(checkupdates | wc -l)

if [ "$1" = "--update" ]; then
    kitty --title update-sys sh -c 'paru -Syu --noconfirm'
fi

# If there aren't any parameters, return the total number of updates
if [ "$1" = "" ]; then
    # Calculate total number of updates
    COUNT=$((PACMAN+AUR))
    # If there are updates, the script will output the following:   Updates
    # If there are no updates, the script will output nothing.

    if [[ "$COUNT" = "0" ]]
    then
        echo ""
    else
        # This Update symbol is RTL. So &#x202d; is left-to-right override.
        echo "  $COUNT"
    fi
    exit 0
fi
