[colors.primary]
background = '#121318'
foreground = '#e3e2e9'

[colors.selection]
text = '#e3e2e9'
background = '#334478'

[colors.cursor]
text = '#121318'
cursor = '#b4c5ff'

[colors.normal]
black   = '#121318'
red     = '#ff7298'
green   = '#7fff93'
yellow  = '#fff972'
blue    = '#9cb0f2'
magenta = '#364476'
cyan    = '#b4c5ff'
white   = '#eff3ff'

[colors.bright]
black   = '#999ca5'
red     = '#ff9fb8'
green   = '#a5ffb3'
yellow  = '#fffba5'
blue    = '#bfcdff'
magenta = '#cad6ff'
cyan    = '#dde4ff'
white   = '#f8faff'
