#!/usr/bin/env bash

ROFI="rofi -dmenu -i -p"

declare -A colorschemes

colorschemes[Dracula]="dracula"
colorschemes[Doom One]="doom-one"
colorschemes[Nightfly]="nightfly"
colorschemes[Monokai Pro]="monokai_pro"
colorschemes[Solarized Dark]="solarized_dark"

choice=$(printf '%s\n' "${!colorschemes[@]}" | sort | ${ROFI} 'Choose a colorscheme' "${@}")
config="${colorschemes["${choice}"]}"

if [ "$choice" ]; then
  # Set the theme for Kitty
  sed -i "s|^include ./themes/.*.conf|include ./themes/$config.conf|g" ~/.config/kitty/kitty.conf
  # Set the theme for AwesomeWM
  sed -i "s|^local colors = require('theme.*')|local colors = require('theme.$config')|g" ~/.config/awesome/theme/theme.lua
  # Restart Awesome
  awesome-client 'awesome.restart()';
  else
   echo "Program terminated." && exit 0
fi

