#!/usr/bin/env bash
# author: unknown
# sentby: MoreChannelNoise (https://www.youtube.com/user/MoreChannelNoise)
# editby: gotbletu (https://www.youtube.com/user/gotbletu)

# demo: https://www.youtube.com/watch?v=kxJClZIXSnM
# info: this is a script to launch other rofi scripts,
#       saves us the trouble of binding multiple hotkeys for each script,
#       when we can just use one hotkey for everything.

declare -A LABELS
declare -A COMMANDS

###
# List of defined 'bangs'

# launch programs
COMMANDS["Apps"]="rofi -show drun -show-icons"
LABELS["Apps"]=""

# Rofi-Powermenu
COMMANDS["Rofi-Powermenu"]="rofi-powermenu"
LABELS["Rofi-Powermenu"]=""

# Rofi-Files
COMMANDS["Rofi-Files"]="rofi-files"
LABELS["Rofi-Files"]=""

# Rofi-Search
COMMANDS["Rofi-Search"]="rofi-search"
LABELS["Rofi-Search"]=""

# Rofi-Watchmenu
COMMANDS["Rofi-Watchmenu"]="rofi-watchmenu"
LABELS["Rofi-Watchmenu"]=""

# Rofi-Beats
COMMANDS["Rofi-Beats"]="rofi-beats"
LABELS["Rofi-Beats"]=""

# Rofi-Maim
COMMANDS["Rofi-Maim"]="rofi-maim"
LABELS["Rofi-Maim"]=""

# Rofi-Weather
COMMANDS["Rofi-Weather"]="rofi-weather"
LABELS["Rofi-Weather"]=""

# Rofi-Kill
COMMANDS["Rofi-Kill"]="rofi-kill"
LABELS["Rofi-Kill"]=""

# Rofi-Pass
COMMANDS["Rofi-Pass"]="rofi-pass"
LABELS["Rofi-Pass"]=""

# Rofi-Calc
COMMANDS["Rofi-Calc"]="rofi -show calc"
LABELS["Rofi-Calc"]=""

# Rofi-Books
COMMANDS["Rofi-Books"]="rofi-books"
LABELS["Rofi-Books"]=""

################################################################################
# do not edit below
################################################################################
##
# Generate menu
##
function print_menu()
{
    for key in ${!LABELS[@]}
    do
  echo "$key    ${LABELS}"
     #   echo "$key    ${LABELS[$key]}"
     # my top version just shows the first field in labels row, not two words side by side
    done
}
##
# Show rofi.
##
function start()
{
    print_menu | sort | rofi -dmenu -p "Rofi-Menu:" 
    # print_menu | sort | rofi -dmenu -mesg ">>> launch your collection of rofi scripts" -i -p "Rofi-Menu: "

}


# Run it
value="$(start)"

# Split input.
# grab upto first space.
choice=${value%%\ *}
# graph remainder, minus space.
input=${value:$((${#choice}+1))}

##
# Cancelled? bail out
##
if test -z ${choice}
then
    exit
fi

# check if choice exists
if test ${COMMANDS[$choice]+isset}
then
    # Execute the choice
    eval echo "Executing: ${COMMANDS[$choice]}"
    eval ${COMMANDS[$choice]}
else
 eval  $choice | rofi
 # prefer my above so I can use this same script to also launch apps like geany or leafpad etc (DK) 
 #   echo "Unknown command: ${choice}" | rofi -dmenu -p "error"
fi
