#!/usr/bin/env bash

ROFI="rofi -dmenu -i -p"

declare -A colorschemes

colorschemes[Dracula]="dracula"
colorschemes[Doom One]="doom-one"
colorschemes[Nightfly]="nightfly"
# colorschemes[Monokai Pro]="monokai_pro"
# colorschemes[Solarized Dark]="solarized_dark"

choice=$(printf '%s\n' "${!colorschemes[@]}" | sort | ${ROFI} 'Choose a colorscheme' "${@}")
config="${colorschemes["${choice}"]}"

kittypath=$(echo $config | sed "s|^|/home/lucas/.config/kitty/themes/|");
awesomepath=$(echo $config | sed "s|^|/home/lucas/.config/awesome/theme/|");


if [ "$choice" ]; then
  # echo $config
  # Set the theme for Kitty
  ln -sfT $kittypath.conf /home/lucas/.config/kitty/colors.conf;
  # Setting the theme for Awesome
  ln -sfT $awesomepath.lua /home/lucas/.config/awesome/theme/theme.lua;
  # Restart Awesome
  awesome-client 'awesome.restart()';
  
  else
   echo "Program terminated." && exit 0
fi

