#!/usr/bin/env bash
#
# Script name: dm-weather
# Description: Simple graphical weather app
# Dependencies: dmenu, curl, yad
# GitLab: https://www.gitlab.com/dwt1/dmscripts
# License: https://www.gitlab.com/dwt1/dmscripts/LICENSE
# Contributors: HostGrady

declare -A weather_location

weather_location[Santo André]="Santo+andre"
weather_location[Seabra]="Seabra"
weather_opts="m" # Always use metric units (celsius)
weather_opts="u" # Always use US units (fahrenheit)
# see: https://github.com/chubin/wttr.in

main() {
  # Here we obtain the location from the list in the config
  # As this is loaded from other file it is technically not defined
  # shellcheck disable=SC2154
  _location="$(printf '%s\n' "${!weather_location[@]}" | sort | rofi -dmenu -i -p "Where do you want to see the weather?")"

  weather_opts+='m'

if [[ "$_location" == "Santo André" ]]; then
    curl -s "https://wttr.in/\"${weather_location[${_location}]}\"?T&${weather_opts}" | yad --text-info --center 
    
elif [[ "$_location" == "Seabra" ]]; then
    curl -s "https://wttr.in/\"${weather_location[${_location}]}\"?T&${weather_opts}" | yad --text-info --center 
fi
}

main 
