#!/bin/bash

# Variables
ROFI="rofi -dmenu -i -p"
wallpaper_dir="${HOME}/Imagens/Wallpapers"
set_bg="feh --bg-scale --no-fehbg --no-xinerama"

main() {
  choice="$(printf "Set\nRandom\nExit" | ${ROFI} "What would you like to do?")" 
  case $choice in
  "Set")
  wallpaper="$(sxiv -t -o "${wallpaper_dir}")"
  ${set_bg} "$wallpaper"
  notify-send "Wallpaper has been updated" -i $wallpaper
  ;;
  "Random")
  valid_paper="No"
  until [ "$valid_paper" = "Yes" ]; do
  pidof "feh" && killall "feh" 
  wallpaper="$(find "${wallpaper_dir}" -type f | shuf -n 1)"
  ${set_bg} "$wallpaper" &
  valid_paper="$(printf "Yes\nNo" | ${ROFI} "Do you like the new wallpaper?")"
done
  ;;
  "Exit") echo "Program terminated" && exit 1;;
esac
}

main
