#!/usr/bin/env bash

LIBRARY="$HOME/Documentos/Media/Livros/"

function main() {
	books=$(find $LIBRARY | grep '\.epub\|\.pdf')
	books=${books//$LIBRARY/"~"}

	line=$(echo "$books" | sort | rofi -matcher fuzzy -dmenu -i -p "Livros")

	exit_code=$?

	line="${line/\~/$LIBRARY}"

	if [ $exit_code == 0 ]; then
		zathura "${line}"
		echo $line
	fi
}

main
