#!/bin/sh

# add more args here according to preference
ARGS="--volume=60"
ROFI="rofi -p "Radios" -dmenu"


notification(){
# change the icon to whatever you want. Make sure your notification server 
# supports it and already configured.

# Now it will receive argument so the user can rename the radio title
# to whatever they want

	notify-send "Playing now: " "$@" --icon=media-tape
}

menu(){
	printf "01. Lofi Girl\n"
	printf "02. Chillhop\n"
	printf "03. Pop Music\n"
	printf "04. Pop Stars\n"
	printf "05. The 2000s\n"
	printf "06. 2000s\n"
  printf "07. Forró\n"
  printf "08. Forró 2\n"
  printf "09. Sertanejo\n"
  printf "10. 90s Rock\n"
  printf "11. RocknRoll Radio\n"
  printf "12. Hip Hop 49\n"
  printf "13. MPB FM"
 ## printf "14. test"
}

main() {
	choice=$(menu | ${ROFI} | cut -d. -f1)

	case $choice in
		01)
			notification "Lofi Girl ☕️🎶";
            URL="https://play.streamafrica.net/lofiradio"
			break
			;;
		02)
			notification "Chillhop ☕️🎶";
            URL="http://stream.zeno.fm/fyn8eh3h5f8uv"
			break
			;;
		03)
			notification "Pop Music ☕️🎶";
            URL="https://zeno.fm/radio/popmusic74vyurvmug0uv/"
			break
			;;
		04)
			notification "Pop Stars ☕️🎶";
            URL="https://zeno.fm/radio/popstars/"
			break
			;;
		05)
			notification "2000s ☕️🎶";
            URL="https://zeno.fm/radio/the-2000s/"
			break
			;;
		06)
			notification "The 2000s ☕️🎶";
            URL="https://zeno.fm/radio/2000-s/"
			break
			;;
    07)
			notification "Forró ☕️🎶";
            URL="https://zeno.fm/radio/forrogk17g5xyqnhvv/"
			break
			;;
    08)
			notification "Forró 2 ☕️🎶";
            URL="https://zeno.fm/radio/forr212a33wptnhvv/"
			break
			;;
    09)
			notification "Sertanejo ☕️🎶";
            URL="https://zeno.fm/radio/sertanejo0wc108upu98uv/"
			break
			;;
    10)
			notification "90s Rock ☕️🎶";
            URL="https://zeno.fm/radio/90s-rock/"
			break
			;;
    11)
			notification "RocknRoll Radio ☕️🎶";
            URL="https://zeno.fm/radio/rocknroll-radio994c7517qs8uv/"
			break
			;;
    12)
			notification "HipHop 49 ☕️🎶";
            URL="https://zeno.fm/radio/hiphop49/"
			break
			;;
  
    13)
			notification "MPB FM ☕️🎶"; 
            URL="https://zeno.fm/radio/musicapopularbrasileira/"
			break
			;;
   # 14)
			# notification "test ☕️🎶"; 
   #          URL="https://onlineradiobox.com/br/kiss/"
			# break
			# ;;
 


	esac
    # run mpv with args and selected url
    # added title arg to make sure the pkill command kills only this instance of mpv
    mpv $ARGS --title="radio-mpv" $URL
}

pkill -f radio-mpv || main
