#!/usr/bin/env bash
#
# Script name: dmqute
# Description: Search your qutebrowswer bookmarks and quickmarks.
# Dependencies: dmenu, librewolf
# GitLab: https://www.gitlab.com/dwt1/dmscripts
# License: https://www.gitlab.com/dwt1/dmscripts/LICENSE
# Contributors: Derek Taylor

# Default Browser
BROWSER=librewolf

declare -A webmarks

webmarks["[gh]"]="https://github.com/Lucas-Martins-Vieira"
webmarks["[lk]"]="https://www.linkedin.com/feed/"
webmarks["[yt]"]="https://www.youtube.com/"
webmarks["[wb]"]="https://web.whatsapp.com/"
webmarks["[tt]"]="https://twitter.com/home"
webmarks["[lb]"]="https://letterboxd.com/"
webmarks["[rd]"]="https://www.reddit.com/"
webmarks["[pt]"]="https://br.pinterest.com/"
webmarks["[sa]"]="https://estudante.estacio.br/disciplinas"
webmarks["[si]"]="https://simulado.estacio.br/alunos/"
webmarks["[es]"]="https://estacio.br/"
webmarks["[op]"]="https://www.crunchyroll.com/pt-br/one-piece"
webmarks["[ox]"]="https://onepieceex.net/"
webmarks["[aw]"]="https://wiki.archlinux.org/"
webmarks["[wm]"]="https://awesomewm.org/"
webmarks["[nf]"]="https://www.nerdfonts.com/"
webmarks["[hc]"]="https://www.color-hex.com/"
webmarks["[cn]"]="https://www.clash.ninja/upgrade-tracker/yc2jjr9yc/home#builders"
webmarks["[lg]"]="https://libgen.is/"
webmarks["[cv]"]="https://www.cursoemvideo.com/login/"

# Piping the above array into dmenu.
# We use "printf '%s\n'" to format the array one item to a line.
# The urls are listed quickmarks first, then the SEPARATOR, and then bookmarks.
choice=$(printf '%s\n' "${!webmarks[@]}" | sort | rofi -dmenu -i -p 'Browser open:' "$@") || exit

# What to do when/if we choose a bookmark/quickmark to view.
if [ "$choice" ]; then
  url=$(echo "${webmarks["${choice}"]}") || exit
	$BROWSER "$url"
  notify-send "Opening: $choice"
# What to do if we just escape without choosing anything.
else
    echo "Program terminated." && exit 0
fi
