return {
  wifi_on = "󰖩 ",
  wifi_off = "󰖪 ",
  updates_on = " ",
  updates_off = "󰅤 ",
  tray_on = " ",
  tray_off = " ",
  bluetooth_on = "󰂯",
  bluetooth_off = "󰂲",
  disk = " ",
  power = "⏻ ",
  launcher = "󰍉 ",
  menu = "󰍜",
  close = "",
  tag = " ",
  battery = {
    hundred = "󰁹",
    ninety = "󰂂",
    eighty = "󰂁",
    seventy = "󰂀",
    sixty = "󰁿",
    fifty = "󰁾",
    forty = "󰁽",
    thirty = "󰁼",
    twenty = "󰁻",
    ten = "󰁺",
  },
  volume = {
    high = "󰕾 ",
    medium = "󰖀 ",
    low = "󰕿 ",
    mute = "󰝟 ",
  },
  notification = {
    normal = "󰂚 ",
    off = "󰂛 ",
    on = "󰂞 ",
    clear = "󰎟 ",
  },
  player = {
    next = "󰒭",
    prev = '󰒮',
    paused = "󰐊",
    playing = "󰏤",
  },
}
