return {
	"MeanderingProgrammer/render-markdown.nvim",
	enabled = true,
	dependencies = { "nvim-treesitter/nvim-treesitter", "nvim-tree/nvim-web-devicons" }, -- if you prefer nvim-web-devicons
	ft = { "markdown" },
	config = function()
		require("render-markdown").setup({
			heading = {
				enabled = false,
			},
			bullet = {
				enabled = false,
				icons = { "•", "", "•", "" },
			},
			dash = {
				enabled = true,
				render_modes = false,
				icon = "─",
				width = "full",
				left_margin = 0,
				priority = nil,
				highlight = "RenderMarkdownDash",
			},
			pipe_table = {
				enabled = false,
				preset = "round",
			},
			sign = {
				enabled = true,
				priority = nil,
				highlight = "RenderMarkdownSign",
			},
			checkbox = {
				enabled = true,
				unchecked = {
					icon = "󰄱",
				},
				checked = {
					icon = "󰄲",
				},
				custom = {
					in_progress = { raw = "[/]", rendered = "󱎖", highlight = "RenderMarkdownTodo" },
					fowarded = { raw = "[>]", rendered = "󰨳", highlight = "RenderMarkdownTodo" },
				},
			},
			code = {
				enabled = true,
				render_modes = false,
				sign = true,
				conceal_delimiters = true,
				language = true,
				position = "left",
				language_icon = true,
				language_name = true,
				language_info = true,
				language_pad = 0,
				disable = {},
				disable_background = { "diff" },
				width = "full",
				left_margin = 0,
				left_pad = 0,
				right_pad = 0,
				min_width = 0,
				border = "hide",
				language_border = "█",
				language_left = "",
				language_right = "",
				above = "▄",
				below = "▀",
				inline = true,
				inline_left = "",
				inline_right = "",
				inline_pad = 0,
				priority = 140,
				highlight = "RenderMarkdownCode",
				highlight_info = "RenderMarkdownCodeInfo",
				highlight_language = nil,
				highlight_border = "RenderMarkdownCodeBorder",
				highlight_fallback = "RenderMarkdownCodeFallback",
				highlight_inline = "RenderMarkdownCodeInline",
				highlight_inline_left = nil,
				highlight_inline_right = nil,
				style = "full",
			},
			yaml = {
				enabled = true,
			},
		})
	end,
}
