#!/usr/bin/env bash

# See the river(1), riverctl(1), and rivertile(1) man pages for complete
# documentation.

# Note: the "Super" modifier is also known as Logo, GUI, Windows, Mod4, etc.
# shellcheck disable=SC1091

# Auto Start
source "$HOME/.config/river/conf/autostart"

# Binds
source "$HOME/.config/river/conf/binds/applications"
source "$HOME/.config/river/conf/binds/river"
source "$HOME/.config/river/conf/binds/media"

# Tags
source "$HOME/.config/river/conf/binds/tags"

# Rules
source "$HOME/.config/river/conf/rules"

# General
source "$HOME/.config/river/conf/general"
